llm:
  # gpt-3.5-turbo or gpt-4
  model: "gpt-3.5-turbo"
nlp:
  server_url: "http://localhost:8080"
memory:
  message_window: 12
extractors:
  summarizer:
    enabled: true
  entities:
    enabled: true
  embeddings:
    messages:
      enabled: true
      provider: "openai"
    documents:
      enabled: true
      provider: "local"
memory_store:
  type: "postgres"
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/?sslmode=disable"
server:
  port: 8000
log:
  level: "info"

