llm:
  # gpt-3.5-turbo or gpt-4
  model: "gpt-3.5-turbo"
nlp:
  server_url: "http://localhost:8080"
memory:
  message_window: 12
extractors:
  summarizer:
    enabled: true
  entities:
    enabled: true
  intent:
    enabled: true
  embeddings:
    enabled: true
    dimensions: 1536
    model: "AdaEmbeddingV2"
#    dimensions: 768
#    model: "local"
memory_store:
  type: "postgres"
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/?sslmode=disable"
server:
  port: 8000
data:
  #  PurgeEvery is the period between hard deletes, in minutes.
  #  If set to 0 or undefined, hard deletes will not be performed.
  purge_every: 60
log:
  level: "info"

