llm:
  # gpt-3.5-turbo or gpt-4
  model: "gpt-3.5-turbo"
memory:
  message_window: 12
extractors:
  summarizer:
    enabled: true
  embeddings:
    enabled: true
    dimensions: 1536
    model: "AdaEmbeddingV2"
memory_store:
  type: "postgres"
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/?sslmode=disable"
server:
  port: 8000
log:
  level: "info"

