llm:
  # gpt-3.5-turbo or gpt-4
  model: "gpt-3.5-turbo"
  azure_openai_endpoint:
  openai_org_id:
nlp:
  server_url: "http://localhost:8080"
memory:
  message_window: 12
extractors:
  summarizer:
    enabled: true
  entities:
    enabled: true
  embeddings:
    enabled: true
    dimensions: 1536
    model: "AdaEmbeddingV2"
#    dimensions: 768
#    model: "local"
memory_store:
  type: "postgres"
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/?sslmode=disable"
server:
  port: 8000
log:
  level: "info"

